### ISSUE TITLE
Binding options parameter prevents certain functionality to stop working

### ISSUE THREAD

**Issue by kylechase** [Kyvis-Labs/ignition-apexcharts-module#1]
When binding the whole object property, certain functionality, like options.xaxis.type do not function properly.  Removing the binding allows the chart to work properly.

Enclosed is an example.
[broken chart with binding.zip](https://github.com/Kyvis-Labs/ignition-apexcharts-module/files/7278333/broken.chart.with.binding.zip)

**Comment by traviscox** [comment]
This issue is now resolved with 1.0.4.
