### ISSUE TITLE
showSeries() and hideSeries() methods

### ISSUE THREAD

**Issue by nikolai-wolterstorff** [Kyvis-Labs/ignition-apexcharts-module#10]
Could we get showSeries() and hideSeries() methods implemented like toggleSeries() in [Issue #8](https://github.com/Kyvis-Labs/ignition-apexcharts-module/issues/8)?

Much appreciated!

**Comment by traviscox** [comment]
Added in [1.0.7](https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.7).
