### ISSUE TITLE
toggleSeries() method returns None

### ISSUE THREAD

**Issue by nikolai-wolterstorff** [Kyvis-Labs/ignition-apexcharts-module#11]
According to the [ApexCharts docs](https://apexcharts.com/docs/methods/#toggleSeries), toggleSeries() should return a boolean for whether the series was hidden or shown. Within Ignition this returns None. Can we get it to return the boolean value?

Thanks

**Comment by traviscox** [comment]
Added in [1.0.7](https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.7).
