### ISSUE TITLE
Toolbar Menu Dark theme background is white

### ISSUE THREAD

**Issue by NaderChinichian** [Kyvis-Labs/ignition-apexcharts-module#12]
In the dark mode of perspective the background of menu is white and the fonts is also white so it is not readable.
![image](https://user-images.githubusercontent.com/46446543/150175211-6c381efe-ad1d-466c-b37b-dbcde64f4ba4.png)

**Comment by nikolai-wolterstorff** [comment]
You need to do this:
![image](https://user-images.githubusercontent.com/37962391/150614711-6588c416-6619-4d7b-835e-afc87f49a7e9.png)
