### ISSUE TITLE
Initial Load Animation

### ISSUE THREAD

**Issue by nikolai-wolterstorff** [Kyvis-Labs/ignition-apexcharts-module#13]
If you observe the example [here](https://apexcharts.com/javascript-chart-demos/line-charts/data-labels/), it has a "bouncy" animation when you initially load the chart. I cannot replicate this with the ApexCharts components in Ignition (tested with the default ApexChart Line component).

I think this would be a great thing to have as it really pulls together the look and feel of the charts.

**Comment by traviscox** [comment]
Thanks for reporting. We had a regression issue. The animation has been fixed in [1.0.7](https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.7).
