### ISSUE TITLE
Adding goals object into the data series prevent chart from rendering

### ISSUE THREAD

**Issue by NaderChinichian** [Kyvis-Labs/ignition-apexcharts-module#14]
Hi kylechase
For the bar chart when I add goals to the data like the following example the data doesn't render at all.  Sometimes changing the chart from bar to pie trigger it and it renders correctly but this only happens for one time until the next opening of the page.

https://apexcharts.com/javascript-chart-demos/bar-charts/bar-with-markers/

**Comment by nikolai-wolterstorff** [comment]
@NaderChinichian does resizing the web browser (if in client) or expanding/collapsing a panel in the designer make the chart show up/render?

**Comment by traviscox** [comment]
There was an issue with the chart re-rendering when updated. Fixed in [1.0.7](https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.7).
