### ISSUE TITLE
Upgrade protection

### ISSUE THREAD

**Issue by JoeriIndenKleef** [Kyvis-Labs/ignition-apexcharts-module#15]
Hi,

Maybe not the best place to ask but I will do it anyway. 
How save is it to use the module in terms of upgrade protection.
Is this module going to be updated for all future versions of Ignition?
Could you please give some insides on this topic?
I really love the module! 
But want to prevent extra work while upgrading Ignition at customers.

**Comment by traviscox** [comment]
Yes, we will continue to update the module for future versions of Ignition.
