### ISSUE TITLE
Pie Chart Animation "Flickering"

### ISSUE THREAD

**Issue by cmwarre** [Kyvis-Labs/ignition-apexcharts-module#17]
I had an older build of the module (from October 2021) that didn't have the same issue so I believe it's a regression or api change somewhere in a recent version?  

# Actual (v1.0.6):
![pie-chart-flickering](https://user-images.githubusercontent.com/1529600/152850861-698c65a6-01a5-4c0a-8eb3-d7c7c7cb6643.gif)

# Expected (v1.0.2):
![pie-chart-working](https://user-images.githubusercontent.com/1529600/152850872-eb1e1356-cc69-4717-a92c-da61fe2c5efb.gif)

My chart settings are below:

`
{
  "chart": {
    "animations": {
      "animateGradually": {
        "delay": 1,
        "enabled": false
      },
      "dynamicAnimation": {
        "enabled": false,
        "speed": 1
      },
      "easing": "linear",
      "enabled": true,
      "speed": 5
    },
    "events": {
      "animationEnd": false,
      "beforeMount": false,
      "beforeResetZoom": false,
      "beforeZoom": false,
      "brushScrolled": false,
      "click": false,
      "dataPointMouseEnter": false,
      "dataPointMouseLeave": false,
      "dataPointSelection": false,
      "legendClick": false,
      "markerClick": false,
      "mounted": false,
      "mouseLeave": false,
      "mouseMove": false,
      "scrolled": false,
      "selection": false,
      "updated": false,
      "zoomed": false
    },
    "type": "pie",
    "width": 380
  },
  "colors": [
    "#9ed23eff",
    "#7864deff",
    "#f06240ff",
    "#d5d5d5ff",
    "#ffc800ff",
    "#b65518ff",
    "#d5d5d5ff"
  ],
  "dataLabels": {
    "enabled": false
  },
  "labels": [
    "Running",
    "Changeover",
    "Downtime",
    "Idle",
    "Upstream",
    "Downstream",
    "Unknown"
  ],
  "legend": {
    "position": "left"
  },
  "responsive": [
    {
      "breakpoint": 600,
      "options": {
        "chart": {
          "width": 300
        },
        "legend": {
          "position": "bottom"
        }
      }
    }
  ],
  "tooltip": {
    "custom": "function (opts) { return opts.w.config.tooltip.values[opts.seriesIndex]; }",
    "values": [
      "Running: 00:17:15",
      "Changeover: 00:01:59",
      "Downtime: 00:00:55",
      "Idle: None",
      "Upstream: None",
      "Downstream: None",
      "Unknown: None"
    ]
  }
}
`

**Comment by traviscox** [comment]
Yep, we had a regression issue. Fixed in [1.0.7](https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.7).
