### ISSUE TITLE
Bar with Markers is not rendering in 1.0.7

### ISSUE THREAD

**Issue by NaderChinichian** [Kyvis-Labs/ignition-apexcharts-module#18]
Bar with Markers is not rendering at all.
https://apexcharts.com/javascript-chart-demos/bar-charts/bar-with-markers/

**Comment by lachguerabdallah** [comment]
same issue in the column chart, the markers do not work..

**Comment by traviscox** [comment]
Fixed the issue in 1.0.8:

[https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.8](https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.8)

**Comment by NaderChinichian** [comment]
Thanks Travis. Very Fast and clean action liek always
