### ISSUE TITLE
Infinite chart refreshing (redrawing) in embedded view

### ISSUE THREAD

**Issue by NaderChinichian** [Kyvis-Labs/ignition-apexcharts-module#20]
When I put the chart inside of a view and use it as an embedded view in another view the chart keeps redrawing forever in runtime mode.
![infinite refreshing](https://user-images.githubusercontent.com/46446543/162288175-dff5d301-1d93-418a-823c-1c9e9e3c725c.gif)

**Comment by NaderChinichian** [comment]
This is only happend in 1.0.8 and not 1.0.6

**Comment by traviscox** [comment]
I will look into this problem over the weekend.

**Comment by NaderChinichian** [comment]
Hi Travis
Did you get some free time to check it? I really stuck with this as 1.0.6 doesn't work with goal setting and 1.0.8 cause this problem and I need time range chart at same time. 
Thanks in Advance

**Comment by traviscox** [comment]
Fixed this issue in 1.0.9:

[https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.9](https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.9)

Can you verify and close the ticket?

**Comment by NaderChinichian** [comment]
Thanks Travis It is fully working now
