### ISSUE TITLE
xaxis labels rotate

### ISSUE THREAD

**Issue by AlwaysABattler** [Kyvis-Labs/ignition-apexcharts-module#21]
Hi Travis,

I'm using the line chart. I am trying to rotate the xaxis labels. It works for the yaxis but not the xaxis. Any ideas? In the image, i tried -45 degrees but i actually want -90 degree.

![image](https://user-images.githubusercontent.com/92848133/177284468-de981470-9652-4cb6-b6a4-d00053b12492.png)

**Comment by nikolai-wolterstorff** [comment]
Try rotateAlways: true.
https://apexcharts.com/docs/options/xaxis/#rotateAlways

**Comment by AlwaysABattler** [comment]
I did look at the that URL but I stopped at rotate 😞. So the issue was between the chair and the computer lol.

**Comment by AlwaysABattler** [comment]
thanks Nikolai
