### ISSUE TITLE
tooltip css

### ISSUE THREAD

**Issue by AlwaysABattler** [Kyvis-Labs/ignition-apexcharts-module#25]
Hi Travis,

I have tried to change the background of the tooltip of the apex charts. Mainly because its too bright for our dark mode but also because it doesn't follow our colour scheme. I found how to change the colour in the docs online (https://apexcharts.com/docs/options/tooltip/). I copied and pasted the following following into my theme file.

.apexcharts-tooltip {
    background: #f3f3f3;
    color: orange;
  }

It changed the color of our text to orange, but the background didn't change. I tried different colors but they did work either. I also tried "background-color" but that didn't work either. Also, do you know how to change the header text color and background color? The equivariant to .ia_popup__header{} in Ignition. I have changed this on popups in our theme file (our custom one not the ignition one). 

Any help on this matter will be greatly appreciated.

**Comment by richardNZ16** [comment]
I also struggled with this a bit, see here:
https://forum.inductiveautomation.com/t/kyvislabs-apexchart-module/55263/45

Try playing around with the tooltip.theme property.

**Comment by AlwaysABattler** [comment]
Thanks Richard.

I have responded to your comments in the ignition forum. Themes do work! So, ill close this issue. Thanks for your help.
