### ISSUE TITLE
Radar chart doesn't fit on view properly

### ISSUE THREAD

**Issue by AlwaysABattler** [Kyvis-Labs/ignition-apexcharts-module#26]
Hi Travis,

If place a radar chart onto flex container view with the position props of grow = 0, shrink = 0 and basis = 100%, I get a scroll bar vertically. I was hoping to make it take up all the real-estate of a view without the need for scroll bars. 

For now, I have changed basis to 98% to get rid of it.

**Comment by richardNZ16** [comment]
I had the same issue, as described here:
https://forum.inductiveautomation.com/t/kyvislabs-apexchart-module/55263/53

The fix is to set the parent view overflow to "hidden".

**Comment by AlwaysABattler** [comment]
Thanks Richard,

I have made this hidden.
