### ISSUE TITLE
yaxis.labels.formatter

### ISSUE THREAD

**Issue by AlwaysABattler** [Kyvis-Labs/ignition-apexcharts-module#28]
Hi Travis,

I don't think the yaxis.labels.formatter is working. 

I copied the example from the apex chart website (https://apexcharts.com/docs/options/yaxis/) but the chart disappears. If i delete it, it comes back. I used "formatter: (value) => { return val }".

please find attached example code:
[radar apex chart y label error.zip](https://github.com/Kyvis-Labs/ignition-apexcharts-module/files/9680264/radar.apex.chart.y.label.error.zip)

**Comment by nikolai-wolterstorff** [comment]
Check out the docs again and look at the example under yaxis.labels.formatter.
https://apexcharts.com/docs/options/yaxis/
This works:
![image](https://user-images.githubusercontent.com/37962391/210806684-c224167e-6513-4c8c-a877-0f3ef4ffd321.png)
