### ISSUE TITLE
Treemap component doesn't work in ignition

### ISSUE THREAD

**Issue by OceanMMouray** [Kyvis-Labs/ignition-apexcharts-module#31]
Hi,

First of all I want to thank you for this great module.

I currently try to use a "treemap" chart to display different defects on a machine (according to the impact time). Unfortunately, I meet a difficulty.

When I set up the graph and add a data series (as shown in the Apex documentation), only one data point is displayed (without the label or value).

![treemapApex](https://user-images.githubusercontent.com/121941086/212864286-c4cc0cac-5dae-421c-9d4a-f53d130499b3.PNG)

With the same configuration, everything is fine with the heatmap component

**Comment by traviscox** [comment]
What version of the Apex Charts are you on? I have it working fine on 1.0.9.

![image](https://user-images.githubusercontent.com/7546864/215283681-33d41792-3198-48f2-9300-001e4886a544.png)

**Comment by OceanMMouray** [comment]
Hello, 

I was in version 1.0.1 I just updated the module and everything works 

Thanks for your help
