### ISSUE TITLE
Delay In Chart Resizing When Parent View is Resized

### ISSUE THREAD

**Issue by willmt10** [Kyvis-Labs/ignition-apexcharts-module#35]
This may be related to Issue #7 .  I'm noticing that charts take a couple seconds to resize after the parent view has resized.  If the parent view shrinks the chart overflows for a couple seconds, if the parent view grows the chart will have some extra whitespace for a couple seconds. I could easily seeing this being something with ApexCharts that we have no control over but wanted to bring it up in case there is a way to fix this.  I have tried both embedding within a FlexContainer and having directly in a Coordinate Container with percent mode active.  Either way it acts the same.  

Here are a few screenshots:

<img width="1490" alt="230201 - Couple Seconds After View Shrink" src="https://user-images.githubusercontent.com/46464679/216139918-3b1f54d5-cd85-49b3-8852-6d5bd7800774.png">
<img width="1490" alt="230201 - Immediately After View Shrink" src="https://user-images.githubusercontent.com/46464679/216139922-e21fc0d1-e8b3-445c-af28-7ad2d8e65fa4.png">
<img width="1489" alt="230201 - Immediately After View Grow" src="https://user-images.githubusercontent.com/46464679/216139924-5ccd80ad-dcc8-40b9-885c-4cc3f1d19318.png">
<img width="1489" alt="230201 - Couple Seconds After View Grow" src="https://user-images.githubusercontent.com/46464679/216139925-daff69a8-d019-42f9-aa1a-9820f9e01970.png">

**Comment by traviscox** [comment]
Can you send over an example project that I can look at figure out what is going on?

**Comment by traviscox** [comment]
Actually, I think that delay is from Apex Chart's animation. You can simply turn that off if you want. Just set options.chart.animations.enabled = false in the config. I also fixed another issue with handling resize in 1.0.13:

[https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.13](https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.13)

**Comment by willmt10** [comment]
Disabling animation sped it up a little bit, but not completely.  Tried 1.0.13 and seemed to help a little, especially in Chrome (still some lag on resize).  Safari is a fair bit slower with the resize.  All in all, it's not a big issue, just something I noticed.  Attached are the views and page config for a simple mocked up test.  Using the dock handle to resize you can see the chart not quite keep up with the resizing - regardless of being nested in an a Flex Container or not.

[Apex_Resize_Issue_Example_2023-02-02_2014.zip](https://github.com/Kyvis-Labs/ignition-apexcharts-module/files/10573165/Apex_Resize_Issue_Example_2023-02-02_2014.zip)

**Comment by traviscox** [comment]
The resize is a lot faster for me. However, I do see a little delay. I don't think there is anything I can do. Might be the nature of this type of chart.

**Comment by willmt10** [comment]
That was my guess too that it was just inherent to the charts.  It's definitely a lot better in Chrome now.  Thanks for checking!
