### ISSUE TITLE
v1.0.14 Possible Formatter Bug

### ISSUE THREAD

**Issue by willmt10** [Kyvis-Labs/ignition-apexcharts-module#36]
I tried installing 1.0.14 and noticed that my formatter function for the `options: dataLabels: style: colors: 0` was no longer working.  Attached is the same export of views I sent in the previous resize issue.  You can see with module version <=1.0.13, the data labels on the bars change between green and red.  Once upgraded to 1.0.14, they show as the same grey color for all data labels.  Is this a bug or has the implementation method for the formatter string changed?

[Apex_Resize_Issue_Example_2023-02-02_2014.zip](https://github.com/Kyvis-Labs/ignition-apexcharts-module/files/10609370/Apex_Resize_Issue_Example_2023-02-02_2014.zip)

**Comment by traviscox** [comment]
Please download 1.0.14 again from the releases page. Somehow the module was uploaded properly.

**Comment by willmt10** [comment]
Looks great now, thanks!
