### ISSUE TITLE
v1.0.14 Chart type "rangeArea" not in enum

### ISSUE THREAD

**Issue by benmusson** [Kyvis-Labs/ignition-apexcharts-module#37]
**v1.0.14**

The chart type _rangeArea_ is working, but shows a key error in the designer.

![image](https://user-images.githubusercontent.com/58087114/222288466-e9c01a34-eeb6-4ef8-b0b7-d0f0e4e7e723.png)

**Comment by traviscox** [comment]
I will add that to the next release. It is just a schema issue but still allows the chart to work and accept that value.
