### ISSUE TITLE
Grid lines for x-axis don't work for Apex chart version 3.36.2

### ISSUE THREAD

**Issue by awaegeVertech** [Kyvis-Labs/ignition-apexcharts-module#40]
Bug found for ApexCharts v3.36.2 where the x-axis lines do not show up. The bug was fixed in apex chart v3.37.

Reference for bug fix in original source code:
https://github.com/apexcharts/apexcharts.js/issues/3580

**Comment by awaegeVertech** [comment]
Created pull request to update min.js to apex chart v3.37.2

**Comment by canblt** [comment]
any updates ?

**Comment by traviscox** [comment]
Sorry for the delay. I have updated to 3.44.0:

[https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.15](https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.15)

**Comment by traviscox** [comment]
Closed due to inactivity

**Comment by traviscox** [comment]
Closed due to inactivity
