### ISSUE TITLE
Add tickAmount to y-axis casues designer crash

### ISSUE THREAD

**Issue by NaderChinichian** [Kyvis-Labs/ignition-apexcharts-module#43]
Add tickAmount to y-axis causes designer crash as shown below:
![tickAmount crash](https://github.com/Kyvis-Labs/ignition-apexcharts-module/assets/46446543/8787e6d7-469c-403e-b595-236e7201f88d)

**Comment by traviscox** [comment]
Yeah, it doesn't like the value "value". I am looking into how to protect this. For now you can just copy and yaxis object, paste the value in a text editor, add tickAmount, copy it again, and paste it in the designer.

**Comment by traviscox** [comment]
Closed due to inactivity
