### ISSUE TITLE
Add boxPlot chart type

### ISSUE THREAD

**Issue by TeslaOwls** [Kyvis-Labs/ignition-apexcharts-module#44]
The boxPlot chart type is not included in the "type" dropdown despite the Javascript seemingly managing it just fine.
Furthermore, boxPlot sometimes showing for a few frames if I add "type: boxPlot" to the props.options, before being hidden by Ignition due to not being listed in the available types.

**Comment by traviscox** [comment]
Added boxPlot in 1.0.15:

[https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.15](https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.15)
