### ISSUE TITLE
 module arg of Apexchart doesn't work

### ISSUE THREAD

**Issue by naderus** [Kyvis-Labs/ignition-apexcharts-module#46]
It seems the module option of Apexchart doesn't work or the module doesn't pass "module" to the the library.
For example, I want to add the multi-select option so I add a selection module to the chart like the following code:

 selection: {
    enabled: true, // Enable selection
  },

// Create the chart instance
const chart = new ApexCharts(document.querySelector('#chart'), {
  series: chartData,
  options: chartOptions,
  modules: [Selection],
});

chart.render();

**Comment by traviscox** [comment]
That would go inside of the options property on the component:

options: {
    chart: {
        selection: {
            enabled: true
        }
    }
}

**Comment by naderus** [comment]
This options you mention here is related to axis select no the data item on chart itself.

**Comment by naderus** [comment]
I find the solution for this by using the state object in options:
{
  "active": {
    "allowMultipleDataPointsSelection": true,
    "filter": {
      "type": "darken",
      "value": 0.2
    }
  }
}
Please close this issue

**Comment by traviscox** [comment]
Awesome!
