### ISSUE TITLE
The Bar and Pie Chart Render Incorrectly in Mobile 

### ISSUE THREAD

**Issue by naderus** [Kyvis-Labs/ignition-apexcharts-module#47]
When opening the web browser and going to mobile mode the Bar chart and Pie chart scale incorrectly and left some empty space is the right side, but in designer with the same width they render correctly.
Also in normal sizes in the Browser, these two charts are OK.
Other charts are totally fine in any mode.
I test in v1.0.14, 1.0.15, 1.0.16.

Here are some screenshots to explain this problem:

![mobile](https://github.com/Kyvis-Labs/ignition-apexcharts-module/assets/143003205/4f4f0581-4800-46fa-bd79-2f16ca8428e1)
![designer](https://github.com/Kyvis-Labs/ignition-apexcharts-module/assets/143003205/89a46804-ef7f-46ec-b7f3-46860c67875f)
![Desktop](https://github.com/Kyvis-Labs/ignition-apexcharts-module/assets/143003205/cf76a820-3429-4cb8-9627-977e95d6fa69)

**Comment by traviscox** [comment]
Closed (duplicate)
