### ISSUE TITLE
Area not filled

### ISSUE THREAD

**Issue by Beetix** [Kyvis-Labs/ignition-apexcharts-module#49]
Hi,

Area charts aren't filled with the configured color.

Ignition Designer:
![image](https://github.com/Kyvis-Labs/ignition-apexcharts-module/assets/10374047/00b694b5-84d4-4729-8e05-234628447d87)

**VS**

Apex Chart documentation fill example:
![image](https://github.com/Kyvis-Labs/ignition-apexcharts-module/assets/10374047/afe9110c-2b7e-4cfb-9c4d-0e5fe3d83359)

This was tested on Ignition 8.1.33 with version 1.0.16 of the module.

**Comment by traviscox** [comment]
You just need to set your chart to type "area"

**Comment by Beetix** [comment]
@traviscox don't know how I could miss that... Thanks !
