### ISSUE TITLE
Component Events Autofill expects event twice

### ISSUE THREAD

**Issue by aaronrai24** [Kyvis-Labs/ignition-apexcharts-module#57]
## Issue
Autofill expects `event.event` to show properties 

![image](https://github.com/Kyvis-Labs/ignition-apexcharts-module/assets/55159220/defe456a-831f-4d22-af0e-ad652e3ed00c)

<img width="518" alt="image" src="https://github.com/Kyvis-Labs/ignition-apexcharts-module/assets/55159220/c625553d-4411-4374-a88d-38ed0574af38">

If you use event.event then you get this error:
`AttributeError: 'com.inductiveautomation.ignition.common.script.ada' object has no attribute 'event'`

## Expected

Using event once(for example: `event.dataPointIndex`) works. This is expected for autofill as well...

**Comment by traviscox** [comment]
I fixed this issue in 1.0.19:

https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.19
