### ISSUE TITLE
toggleSeries() method

### ISSUE THREAD

**Issue by nikolai-wolterstorff** [Kyvis-Labs/ignition-apexcharts-module#8]
Is it possible to expose the toggleSeries() method as described in [apex charts issue 111](https://github.com/apexcharts/apexcharts.js/issues/111)?
Or to be able to create custom Javascript methods in props>options>chart>events (override boolean value for event) to be able to use this method?

I am trying to initialize the chart with certain series unselected in the legend.

Thank you

**Comment by traviscox** [comment]
The function was implemented in 1.0.6. See the release:

[https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.6](https://github.com/Kyvis-Labs/ignition-apexcharts-module/releases/tag/1.0.6)
