### ISSUE TITLE
Area Chart with Historian query

### ISSUE THREAD

**Issue by tamerplc** [Kyvis-Labs/ignition-apexcharts-module#9]
Hi @traviscox  
chart graph (Area)totally updated (Just like flash for all Graph)  when binding with Tag History (RealTime) , not like the ignition XY chart ONLY new value updated while the rest pf graph just move .

**Comment by kylechase** [comment]
Can you please provide a simple example for this? I can import and take a look.

**Comment by tamerplc** [comment]
issue closed due to wrong setting
